version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  # Below is the definition of the build-and-test job to build and test the app.
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn clean test jacoco:report coveralls:report
workflows:
  # the regression workflow
  regression:
    jobs:
      - build-and-test
